package serverruntime

import (
	"log/slog"

	"go.uber.org/fx"
	"go.uber.org/fx/fxevent"

	"github.com/memohai/memoh/internal/accounts"
	"github.com/memohai/memoh/internal/acl"
	audiopkg "github.com/memohai/memoh/internal/audio"
	"github.com/memohai/memoh/internal/bind"
	"github.com/memohai/memoh/internal/boot"
	"github.com/memohai/memoh/internal/botgroups"
	"github.com/memohai/memoh/internal/bots"
	"github.com/memohai/memoh/internal/browsercontexts"
	"github.com/memohai/memoh/internal/channel"
	"github.com/memohai/memoh/internal/channel/adapters/local"
	"github.com/memohai/memoh/internal/channel/identities"
	"github.com/memohai/memoh/internal/compaction"
	"github.com/memohai/memoh/internal/connectapi"
	"github.com/memohai/memoh/internal/conversation"
	emailpkg "github.com/memohai/memoh/internal/email"
	"github.com/memohai/memoh/internal/eventbus"
	"github.com/memohai/memoh/internal/handlers"
	"github.com/memohai/memoh/internal/heartbeat"
	"github.com/memohai/memoh/internal/integrations"
	"github.com/memohai/memoh/internal/mcp"
	memprovider "github.com/memohai/memoh/internal/memory/adapters"
	"github.com/memohai/memoh/internal/message/event"
	"github.com/memohai/memoh/internal/models"
	"github.com/memohai/memoh/internal/policy"
	"github.com/memohai/memoh/internal/schedule"
	"github.com/memohai/memoh/internal/searchproviders"
	"github.com/memohai/memoh/internal/settings"
	"github.com/memohai/memoh/internal/toolapproval"
	"github.com/memohai/memoh/internal/workspace"
)

func RunServe() {
	fx.New(options()).Run()
}

func options() fx.Option {
	return fx.Options(
		fx.Provide(
			provideConfig,
			boot.ProvideRuntimeConfig,
			provideLogger,
			provideContainerService,
			provideOverlayProviderRegistry,
			provideNetworkService,
			provideNetworkController,
			provideDBConn,
			providePostgresStore,
			provideDBQueries,
			provideEventProducerQueries,
			provideAccountStore,
			provideWorkspaceManager,
			provideWorkspaceExecutorProvider,
			provideMemoryLLM,
			memprovider.NewService,
			botgroups.NewService,
			integrations.NewService,
			provideMemoryProviderRegistry,
			models.NewService,
			bots.NewService,
			provideRBACService,
			accounts.NewService,
			acl.NewService,
			settings.NewService,
			toolapproval.NewService,
			provideProvidersService,
			searchproviders.NewService,
			browsercontexts.NewService,
			policy.NewService,
			mcp.NewConnectionService,
			conversation.NewService,
			identities.NewService,
			bind.NewService,
			event.NewHub,
			provideAudioRegistry,
			audiopkg.NewService,
			provideAudioTempStore,
			emailpkg.NewDBOAuthTokenStore,
			provideEmailRegistry,
			emailpkg.NewService,
			emailpkg.NewOutboxService,
			provideEmailChatTriggerer,
			provideEmailTrigger,
			emailpkg.NewManager,
			provideRouteService,
			provideSessionService,
			provideMessageService,
			provideMediaService,
			providePipeline,
			provideEventStore,
			provideDiscussDriver,
			local.NewRouteHub,
			provideChannelRegistry,
			channel.NewStore,
			provideRunnerServiceClient,
			provideRunnerDispatcher,
			provideChannelRouter,
			provideChannelManager,
			provideChannelLifecycleService,
			provideScheduleTriggerer,
			provideHeartbeatSessionCreator,
			provideScheduleSessionCreator,
			schedule.NewService,
			provideHeartbeatTriggerer,
			heartbeat.NewService,
			compaction.NewService,
			eventbus.NewProducer,
			provideServiceAuthSigner,
			provideServiceAuthVerifier,
			provideInternalAuthService,
			provideRunnerSupportService,
			connectapi.NewAuthService,
			connectapi.NewUserService,
			provideConnectBotService,
			connectapi.NewBotGroupService,
			connectapi.NewIntegrationAdminService,
			connectapi.NewIntegrationGatewayService,
			connectapi.NewSettingsService,
			connectapi.NewProviderService,
			connectapi.NewModelService,
			connectapi.NewSearchProviderService,
			connectapi.NewBrowserContextService,
			connectapi.NewMemoryProviderService,
			connectapi.NewMemoryService,
			connectapi.NewChannelService,
			connectapi.NewNetworkService,
			connectapi.NewEmailProviderService,
			connectapi.NewEmailBindingService,
			connectapi.NewEmailOutboxService,
			connectapi.NewHealthService,
			provideConnectChatService,
			connectapi.NewContainerService,
			connectapi.NewMcpService,
			connectapi.NewScheduleService,
			connectapi.NewSkillService,
			connectapi.NewSpeechService,
			connectapi.NewSupermarketService,
			connectapi.NewToolApprovalService,
			connectapi.NewUsageService,
			provideServerHandler(connectapi.NewAuthHandler),
			provideServerHandler(connectapi.NewUserHandler),
			provideServerHandler(connectapi.NewBotHandler),
			provideServerHandler(connectapi.NewBotGroupHandler),
			provideServerHandler(connectapi.NewIntegrationAdminHandler),
			provideServerHandler(connectapi.NewIntegrationGatewayHandler),
			provideServerHandler(connectapi.NewSettingsHandler),
			provideServerHandler(connectapi.NewProviderHandler),
			provideServerHandler(connectapi.NewModelHandler),
			provideServerHandler(connectapi.NewSearchProviderHandler),
			provideServerHandler(connectapi.NewBrowserContextHandler),
			provideServerHandler(connectapi.NewMemoryProviderHandler),
			provideServerHandler(connectapi.NewMemoryHandler),
			provideServerHandler(connectapi.NewChannelHandler),
			provideServerHandler(connectapi.NewNetworkHandler),
			provideServerHandler(connectapi.NewEmailProviderHandler),
			provideServerHandler(connectapi.NewEmailBindingHandler),
			provideServerHandler(connectapi.NewEmailOutboxHandler),
			provideServerHandler(connectapi.NewHealthHandler),
			provideServerHandler(connectapi.NewChatHandler),
			provideServerHandler(connectapi.NewContainerHandler),
			provideServerHandler(connectapi.NewMcpHandler),
			provideServerHandler(connectapi.NewScheduleHandler),
			provideServerHandler(connectapi.NewSkillHandler),
			provideServerHandler(connectapi.NewSpeechHandler),
			provideServerHandler(connectapi.NewSupermarketHandler),
			provideServerHandler(connectapi.NewToolApprovalHandler),
			provideServerHandler(connectapi.NewUsageHandler),
			provideServerHandler(connectapi.NewInternalAuthHandler),
			provideServerHandler(connectapi.NewRunnerSupportHandler),
			provideContainerdHandler,
			provideFederationGateway,
			provideConnectMcpFederationGateway,
			provideConnectSkillRootResolver,
			provideToolGatewayService,
			provideServerHandler(handlers.NewPingHandler),
			provideServerHandler(provideAuthHandler),
			provideServerHandler(provideMemoryHandler),
			provideServerHandler(provideMessageHandler),
			provideServerHandler(provideSessionHandler),
			provideServerHandler(handlers.NewProvidersHandler),
			provideServerHandler(handlers.NewProviderOAuthHandler),
			provideServerHandler(handlers.NewSearchProvidersHandler),
			provideServerHandler(handlers.NewModelsHandler),
			provideServerHandler(handlers.NewSettingsHandler),
			provideServerHandler(handlers.NewACLHandler),
			provideServerHandler(handlers.NewBindHandler),
			provideServerHandler(handlers.NewScheduleHandler),
			provideServerHandler(handlers.NewHeartbeatHandler),
			provideServerHandler(handlers.NewCompactionHandler),
			provideServerHandler(handlers.NewChannelHandler),
			provideServerHandler(handlers.NewIAMHandler),
			provideServerHandler(provideUsersHandler),
			provideServerHandler(handlers.NewMemoryProvidersHandler),
			provideServerHandler(handlers.NewNetworkHandler),
			provideServerHandler(handlers.NewAudioHandler),
			provideServerHandler(handlers.NewBotAudioHandler),
			provideServerHandler(handlers.NewEmailProvidersHandler),
			provideServerHandler(handlers.NewEmailBindingsHandler),
			provideServerHandler(handlers.NewEmailOutboxHandler),
			provideServerHandler(handlers.NewEmailWebhookHandler),
			provideServerHandler(provideEmailOAuthHandler),
			provideServerHandler(handlers.NewMCPHandler),
			provideServerHandler(handlers.NewMCPOAuthHandler),
			provideOAuthService,
			provideServerHandler(handlers.NewTokenUsageHandler),
			provideServerHandler(handlers.NewSessionInfoHandler),
			provideServerHandler(handlers.NewBrowserContextsHandler),
			provideServerHandler(handlers.NewSupermarketHandler),
			provideServer,
		),
		fx.Invoke(
			startRegistrySync,
			startAudioProviderBootstrap,
			startMemoryProviderBootstrap,
			startSearchProviderBootstrap,
			startEmailManager,
			startContainerReconciliation,
			startAudioTempStoreCleanup,
			startServer,
		),
		fx.WithLogger(func(logger *slog.Logger) fxevent.Logger {
			return &fxevent.SlogLogger{Logger: logger.With(slog.String("component", "fx"))}
		}),
	)
}

func provideConnectMcpFederationGateway(gateway *handlers.MCPFederationGateway) connectapi.McpFederationGateway {
	return gateway
}

func provideConnectSkillRootResolver(manager *workspace.Manager) connectapi.SkillRootResolver {
	return manager
}
