apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../kubernetes
images:
  - name: ghcr.io/stringke/server
    newTag: k8s-dev
  - name: ghcr.io/stringke/browser
    newTag: k8s-dev
