[tasks.dev]
alias = "dev"
description = "Start web development server"
run = "vp run --filter @stringke/web dev"
depends = [
  "//:pnpm-install",
  "//:sdk-generate",
]

[tasks.build]
description = "Build web"
run = "vp run --filter @stringke/web build"
depends = [
  "//:pnpm-install",
  "//:sdk-generate",
]

[tasks.start]
description = "Start web"
run = "vp run --filter @stringke/web start"
depends = [
  "//:pnpm-install",
  "//:sdk-generate",
]
