// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_run_leases.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeAgentRunLease = `-- name: CompleteAgentRunLease :one
UPDATE agent_run_leases
SET completed_at = now(),
    updated_at = now()
WHERE run_id = $1
  AND completed_at IS NULL
RETURNING run_id, runner_instance_id, bot_id, bot_group_id, session_id, user_id, permission_snapshot_version, allowed_tool_scopes, workspace_executor_target, workspace_id, expires_at, lease_version, revoked_at, completed_at, created_at, updated_at
`

func (q *Queries) CompleteAgentRunLease(ctx context.Context, runID pgtype.UUID) (AgentRunLease, error) {
	row := q.db.QueryRow(ctx, completeAgentRunLease, runID)
	var i AgentRunLease
	err := row.Scan(
		&i.RunID,
		&i.RunnerInstanceID,
		&i.BotID,
		&i.BotGroupID,
		&i.SessionID,
		&i.UserID,
		&i.PermissionSnapshotVersion,
		&i.AllowedToolScopes,
		&i.WorkspaceExecutorTarget,
		&i.WorkspaceID,
		&i.ExpiresAt,
		&i.LeaseVersion,
		&i.RevokedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentRunLease = `-- name: CreateAgentRunLease :one
INSERT INTO agent_run_leases (
  run_id,
  runner_instance_id,
  bot_id,
  bot_group_id,
  session_id,
  user_id,
  permission_snapshot_version,
  allowed_tool_scopes,
  workspace_executor_target,
  workspace_id,
  expires_at,
  lease_version
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8::text[],
  $9,
  $10,
  $11,
  $12
)
RETURNING run_id, runner_instance_id, bot_id, bot_group_id, session_id, user_id, permission_snapshot_version, allowed_tool_scopes, workspace_executor_target, workspace_id, expires_at, lease_version, revoked_at, completed_at, created_at, updated_at
`

type CreateAgentRunLeaseParams struct {
	RunID                     pgtype.UUID        `json:"run_id"`
	RunnerInstanceID          string             `json:"runner_instance_id"`
	BotID                     pgtype.UUID        `json:"bot_id"`
	BotGroupID                pgtype.UUID        `json:"bot_group_id"`
	SessionID                 pgtype.UUID        `json:"session_id"`
	UserID                    pgtype.UUID        `json:"user_id"`
	PermissionSnapshotVersion int64              `json:"permission_snapshot_version"`
	AllowedToolScopes         []string           `json:"allowed_tool_scopes"`
	WorkspaceExecutorTarget   string             `json:"workspace_executor_target"`
	WorkspaceID               string             `json:"workspace_id"`
	ExpiresAt                 pgtype.Timestamptz `json:"expires_at"`
	LeaseVersion              int64              `json:"lease_version"`
}

func (q *Queries) CreateAgentRunLease(ctx context.Context, arg CreateAgentRunLeaseParams) (AgentRunLease, error) {
	row := q.db.QueryRow(ctx, createAgentRunLease,
		arg.RunID,
		arg.RunnerInstanceID,
		arg.BotID,
		arg.BotGroupID,
		arg.SessionID,
		arg.UserID,
		arg.PermissionSnapshotVersion,
		arg.AllowedToolScopes,
		arg.WorkspaceExecutorTarget,
		arg.WorkspaceID,
		arg.ExpiresAt,
		arg.LeaseVersion,
	)
	var i AgentRunLease
	err := row.Scan(
		&i.RunID,
		&i.RunnerInstanceID,
		&i.BotID,
		&i.BotGroupID,
		&i.SessionID,
		&i.UserID,
		&i.PermissionSnapshotVersion,
		&i.AllowedToolScopes,
		&i.WorkspaceExecutorTarget,
		&i.WorkspaceID,
		&i.ExpiresAt,
		&i.LeaseVersion,
		&i.RevokedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireAgentRunLeases = `-- name: ExpireAgentRunLeases :execrows
UPDATE agent_run_leases
SET revoked_at = COALESCE(revoked_at, now()),
    updated_at = now()
WHERE expires_at <= now()
  AND revoked_at IS NULL
  AND completed_at IS NULL
`

func (q *Queries) ExpireAgentRunLeases(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireAgentRunLeases)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveAgentRunLease = `-- name: GetActiveAgentRunLease :one
SELECT run_id, runner_instance_id, bot_id, bot_group_id, session_id, user_id, permission_snapshot_version, allowed_tool_scopes, workspace_executor_target, workspace_id, expires_at, lease_version, revoked_at, completed_at, created_at, updated_at
FROM agent_run_leases
WHERE run_id = $1
  AND revoked_at IS NULL
  AND completed_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetActiveAgentRunLease(ctx context.Context, runID pgtype.UUID) (AgentRunLease, error) {
	row := q.db.QueryRow(ctx, getActiveAgentRunLease, runID)
	var i AgentRunLease
	err := row.Scan(
		&i.RunID,
		&i.RunnerInstanceID,
		&i.BotID,
		&i.BotGroupID,
		&i.SessionID,
		&i.UserID,
		&i.PermissionSnapshotVersion,
		&i.AllowedToolScopes,
		&i.WorkspaceExecutorTarget,
		&i.WorkspaceID,
		&i.ExpiresAt,
		&i.LeaseVersion,
		&i.RevokedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentRunLease = `-- name: GetAgentRunLease :one
SELECT run_id, runner_instance_id, bot_id, bot_group_id, session_id, user_id, permission_snapshot_version, allowed_tool_scopes, workspace_executor_target, workspace_id, expires_at, lease_version, revoked_at, completed_at, created_at, updated_at
FROM agent_run_leases
WHERE run_id = $1
`

func (q *Queries) GetAgentRunLease(ctx context.Context, runID pgtype.UUID) (AgentRunLease, error) {
	row := q.db.QueryRow(ctx, getAgentRunLease, runID)
	var i AgentRunLease
	err := row.Scan(
		&i.RunID,
		&i.RunnerInstanceID,
		&i.BotID,
		&i.BotGroupID,
		&i.SessionID,
		&i.UserID,
		&i.PermissionSnapshotVersion,
		&i.AllowedToolScopes,
		&i.WorkspaceExecutorTarget,
		&i.WorkspaceID,
		&i.ExpiresAt,
		&i.LeaseVersion,
		&i.RevokedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAgentRunLease = `-- name: RevokeAgentRunLease :one
UPDATE agent_run_leases
SET revoked_at = now(),
    updated_at = now()
WHERE run_id = $1
  AND revoked_at IS NULL
RETURNING run_id, runner_instance_id, bot_id, bot_group_id, session_id, user_id, permission_snapshot_version, allowed_tool_scopes, workspace_executor_target, workspace_id, expires_at, lease_version, revoked_at, completed_at, created_at, updated_at
`

func (q *Queries) RevokeAgentRunLease(ctx context.Context, runID pgtype.UUID) (AgentRunLease, error) {
	row := q.db.QueryRow(ctx, revokeAgentRunLease, runID)
	var i AgentRunLease
	err := row.Scan(
		&i.RunID,
		&i.RunnerInstanceID,
		&i.BotID,
		&i.BotGroupID,
		&i.SessionID,
		&i.UserID,
		&i.PermissionSnapshotVersion,
		&i.AllowedToolScopes,
		&i.WorkspaceExecutorTarget,
		&i.WorkspaceID,
		&i.ExpiresAt,
		&i.LeaseVersion,
		&i.RevokedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const validateActiveAgentRunLease = `-- name: ValidateActiveAgentRunLease :one
SELECT run_id, runner_instance_id, bot_id, bot_group_id, session_id, user_id, permission_snapshot_version, allowed_tool_scopes, workspace_executor_target, workspace_id, expires_at, lease_version, revoked_at, completed_at, created_at, updated_at
FROM agent_run_leases
WHERE run_id = $1
  AND runner_instance_id = $2
  AND lease_version = $3
  AND bot_id = $4
  AND session_id = $5
  AND workspace_id = $6
  AND workspace_executor_target = $7
  AND revoked_at IS NULL
  AND completed_at IS NULL
  AND expires_at > now()
`

type ValidateActiveAgentRunLeaseParams struct {
	RunID                   pgtype.UUID `json:"run_id"`
	RunnerInstanceID        string      `json:"runner_instance_id"`
	LeaseVersion            int64       `json:"lease_version"`
	BotID                   pgtype.UUID `json:"bot_id"`
	SessionID               pgtype.UUID `json:"session_id"`
	WorkspaceID             string      `json:"workspace_id"`
	WorkspaceExecutorTarget string      `json:"workspace_executor_target"`
}

func (q *Queries) ValidateActiveAgentRunLease(ctx context.Context, arg ValidateActiveAgentRunLeaseParams) (AgentRunLease, error) {
	row := q.db.QueryRow(ctx, validateActiveAgentRunLease,
		arg.RunID,
		arg.RunnerInstanceID,
		arg.LeaseVersion,
		arg.BotID,
		arg.SessionID,
		arg.WorkspaceID,
		arg.WorkspaceExecutorTarget,
	)
	var i AgentRunLease
	err := row.Scan(
		&i.RunID,
		&i.RunnerInstanceID,
		&i.BotID,
		&i.BotGroupID,
		&i.SessionID,
		&i.UserID,
		&i.PermissionSnapshotVersion,
		&i.AllowedToolScopes,
		&i.WorkspaceExecutorTarget,
		&i.WorkspaceID,
		&i.ExpiresAt,
		&i.LeaseVersion,
		&i.RevokedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
