// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: bot_groups.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBotsInGroup = `-- name: CountBotsInGroup :one
SELECT count(*)::bigint
FROM bots
WHERE group_id = $1
`

func (q *Queries) CountBotsInGroup(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBotsInGroup, groupID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createBotGroup = `-- name: CreateBotGroup :one
INSERT INTO bot_groups (owner_user_id, name, description, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_user_id, name, description, metadata, created_at, updated_at
`

type CreateBotGroupParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateBotGroup(ctx context.Context, arg CreateBotGroupParams) (BotGroup, error) {
	row := q.db.QueryRow(ctx, createBotGroup,
		arg.OwnerUserID,
		arg.Name,
		arg.Description,
		arg.Metadata,
	)
	var i BotGroup
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBotGroup = `-- name: DeleteBotGroup :exec
DELETE FROM bot_groups
WHERE id = $1
`

func (q *Queries) DeleteBotGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBotGroup, id)
	return err
}

const deleteBotGroupSettings = `-- name: DeleteBotGroupSettings :exec
DELETE FROM bot_group_settings
WHERE group_id = $1
`

func (q *Queries) DeleteBotGroupSettings(ctx context.Context, groupID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBotGroupSettings, groupID)
	return err
}

const getBotGroupByID = `-- name: GetBotGroupByID :one
SELECT id, owner_user_id, name, description, metadata, created_at, updated_at
FROM bot_groups
WHERE id = $1
`

func (q *Queries) GetBotGroupByID(ctx context.Context, id pgtype.UUID) (BotGroup, error) {
	row := q.db.QueryRow(ctx, getBotGroupByID, id)
	var i BotGroup
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotGroupByOwnerAndID = `-- name: GetBotGroupByOwnerAndID :one
SELECT id, owner_user_id, name, description, metadata, created_at, updated_at
FROM bot_groups
WHERE owner_user_id = $1
  AND id = $2
`

type GetBotGroupByOwnerAndIDParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetBotGroupByOwnerAndID(ctx context.Context, arg GetBotGroupByOwnerAndIDParams) (BotGroup, error) {
	row := q.db.QueryRow(ctx, getBotGroupByOwnerAndID, arg.OwnerUserID, arg.ID)
	var i BotGroup
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotGroupSettings = `-- name: GetBotGroupSettings :one
SELECT group_id, timezone, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, heartbeat_model_id, compaction_enabled, compaction_threshold, compaction_ratio, compaction_model_id, title_model_id, image_model_id, discuss_probe_model_id, tts_model_id, transcription_model_id, browser_context_id, persist_full_tool_results, show_tool_calls_in_im, tool_approval_config, overlay_provider, overlay_enabled, overlay_config, metadata, updated_at
FROM bot_group_settings
WHERE group_id = $1
`

func (q *Queries) GetBotGroupSettings(ctx context.Context, groupID pgtype.UUID) (BotGroupSetting, error) {
	row := q.db.QueryRow(ctx, getBotGroupSettings, groupID)
	var i BotGroupSetting
	err := row.Scan(
		&i.GroupID,
		&i.Timezone,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.HeartbeatModelID,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionRatio,
		&i.CompactionModelID,
		&i.TitleModelID,
		&i.ImageModelID,
		&i.DiscussProbeModelID,
		&i.TtsModelID,
		&i.TranscriptionModelID,
		&i.BrowserContextID,
		&i.PersistFullToolResults,
		&i.ShowToolCallsInIm,
		&i.ToolApprovalConfig,
		&i.OverlayProvider,
		&i.OverlayEnabled,
		&i.OverlayConfig,
		&i.Metadata,
		&i.UpdatedAt,
	)
	return i, err
}

const listBotGroupsByOwner = `-- name: ListBotGroupsByOwner :many
SELECT id, owner_user_id, name, description, metadata, created_at, updated_at
FROM bot_groups
WHERE owner_user_id = $1
ORDER BY name ASC, created_at DESC
`

func (q *Queries) ListBotGroupsByOwner(ctx context.Context, ownerUserID pgtype.UUID) ([]BotGroup, error) {
	rows, err := q.db.Query(ctx, listBotGroupsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotGroup
	for rows.Next() {
		var i BotGroup
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBotGroup = `-- name: UpdateBotGroup :one
UPDATE bot_groups
SET name = $1,
    description = $2,
    metadata = $3,
    updated_at = now()
WHERE id = $4
RETURNING id, owner_user_id, name, description, metadata, created_at, updated_at
`

type UpdateBotGroupParams struct {
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Metadata    []byte      `json:"metadata"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateBotGroup(ctx context.Context, arg UpdateBotGroupParams) (BotGroup, error) {
	row := q.db.QueryRow(ctx, updateBotGroup,
		arg.Name,
		arg.Description,
		arg.Metadata,
		arg.ID,
	)
	var i BotGroup
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBotGroupSettings = `-- name: UpsertBotGroupSettings :one
INSERT INTO bot_group_settings (
  group_id,
  timezone,
  language,
  reasoning_enabled,
  reasoning_effort,
  chat_model_id,
  search_provider_id,
  memory_provider_id,
  heartbeat_enabled,
  heartbeat_interval,
  heartbeat_prompt,
  heartbeat_model_id,
  compaction_enabled,
  compaction_threshold,
  compaction_ratio,
  compaction_model_id,
  title_model_id,
  image_model_id,
  discuss_probe_model_id,
  tts_model_id,
  transcription_model_id,
  browser_context_id,
  persist_full_tool_results,
  show_tool_calls_in_im,
  tool_approval_config,
  overlay_provider,
  overlay_enabled,
  overlay_config,
  metadata
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22,
  $23,
  $24,
  $25,
  $26,
  $27,
  $28,
  $29
)
ON CONFLICT (group_id) DO UPDATE SET
  timezone = EXCLUDED.timezone,
  language = EXCLUDED.language,
  reasoning_enabled = EXCLUDED.reasoning_enabled,
  reasoning_effort = EXCLUDED.reasoning_effort,
  chat_model_id = EXCLUDED.chat_model_id,
  search_provider_id = EXCLUDED.search_provider_id,
  memory_provider_id = EXCLUDED.memory_provider_id,
  heartbeat_enabled = EXCLUDED.heartbeat_enabled,
  heartbeat_interval = EXCLUDED.heartbeat_interval,
  heartbeat_prompt = EXCLUDED.heartbeat_prompt,
  heartbeat_model_id = EXCLUDED.heartbeat_model_id,
  compaction_enabled = EXCLUDED.compaction_enabled,
  compaction_threshold = EXCLUDED.compaction_threshold,
  compaction_ratio = EXCLUDED.compaction_ratio,
  compaction_model_id = EXCLUDED.compaction_model_id,
  title_model_id = EXCLUDED.title_model_id,
  image_model_id = EXCLUDED.image_model_id,
  discuss_probe_model_id = EXCLUDED.discuss_probe_model_id,
  tts_model_id = EXCLUDED.tts_model_id,
  transcription_model_id = EXCLUDED.transcription_model_id,
  browser_context_id = EXCLUDED.browser_context_id,
  persist_full_tool_results = EXCLUDED.persist_full_tool_results,
  show_tool_calls_in_im = EXCLUDED.show_tool_calls_in_im,
  tool_approval_config = EXCLUDED.tool_approval_config,
  overlay_provider = EXCLUDED.overlay_provider,
  overlay_enabled = EXCLUDED.overlay_enabled,
  overlay_config = EXCLUDED.overlay_config,
  metadata = EXCLUDED.metadata,
  updated_at = now()
RETURNING group_id, timezone, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, heartbeat_model_id, compaction_enabled, compaction_threshold, compaction_ratio, compaction_model_id, title_model_id, image_model_id, discuss_probe_model_id, tts_model_id, transcription_model_id, browser_context_id, persist_full_tool_results, show_tool_calls_in_im, tool_approval_config, overlay_provider, overlay_enabled, overlay_config, metadata, updated_at
`

type UpsertBotGroupSettingsParams struct {
	GroupID                pgtype.UUID `json:"group_id"`
	Timezone               pgtype.Text `json:"timezone"`
	Language               pgtype.Text `json:"language"`
	ReasoningEnabled       pgtype.Bool `json:"reasoning_enabled"`
	ReasoningEffort        pgtype.Text `json:"reasoning_effort"`
	ChatModelID            pgtype.UUID `json:"chat_model_id"`
	SearchProviderID       pgtype.UUID `json:"search_provider_id"`
	MemoryProviderID       pgtype.UUID `json:"memory_provider_id"`
	HeartbeatEnabled       pgtype.Bool `json:"heartbeat_enabled"`
	HeartbeatInterval      pgtype.Int4 `json:"heartbeat_interval"`
	HeartbeatPrompt        pgtype.Text `json:"heartbeat_prompt"`
	HeartbeatModelID       pgtype.UUID `json:"heartbeat_model_id"`
	CompactionEnabled      pgtype.Bool `json:"compaction_enabled"`
	CompactionThreshold    pgtype.Int4 `json:"compaction_threshold"`
	CompactionRatio        pgtype.Int4 `json:"compaction_ratio"`
	CompactionModelID      pgtype.UUID `json:"compaction_model_id"`
	TitleModelID           pgtype.UUID `json:"title_model_id"`
	ImageModelID           pgtype.UUID `json:"image_model_id"`
	DiscussProbeModelID    pgtype.UUID `json:"discuss_probe_model_id"`
	TtsModelID             pgtype.UUID `json:"tts_model_id"`
	TranscriptionModelID   pgtype.UUID `json:"transcription_model_id"`
	BrowserContextID       pgtype.UUID `json:"browser_context_id"`
	PersistFullToolResults pgtype.Bool `json:"persist_full_tool_results"`
	ShowToolCallsInIm      pgtype.Bool `json:"show_tool_calls_in_im"`
	ToolApprovalConfig     []byte      `json:"tool_approval_config"`
	OverlayProvider        pgtype.Text `json:"overlay_provider"`
	OverlayEnabled         pgtype.Bool `json:"overlay_enabled"`
	OverlayConfig          []byte      `json:"overlay_config"`
	Metadata               []byte      `json:"metadata"`
}

func (q *Queries) UpsertBotGroupSettings(ctx context.Context, arg UpsertBotGroupSettingsParams) (BotGroupSetting, error) {
	row := q.db.QueryRow(ctx, upsertBotGroupSettings,
		arg.GroupID,
		arg.Timezone,
		arg.Language,
		arg.ReasoningEnabled,
		arg.ReasoningEffort,
		arg.ChatModelID,
		arg.SearchProviderID,
		arg.MemoryProviderID,
		arg.HeartbeatEnabled,
		arg.HeartbeatInterval,
		arg.HeartbeatPrompt,
		arg.HeartbeatModelID,
		arg.CompactionEnabled,
		arg.CompactionThreshold,
		arg.CompactionRatio,
		arg.CompactionModelID,
		arg.TitleModelID,
		arg.ImageModelID,
		arg.DiscussProbeModelID,
		arg.TtsModelID,
		arg.TranscriptionModelID,
		arg.BrowserContextID,
		arg.PersistFullToolResults,
		arg.ShowToolCallsInIm,
		arg.ToolApprovalConfig,
		arg.OverlayProvider,
		arg.OverlayEnabled,
		arg.OverlayConfig,
		arg.Metadata,
	)
	var i BotGroupSetting
	err := row.Scan(
		&i.GroupID,
		&i.Timezone,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.HeartbeatModelID,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionRatio,
		&i.CompactionModelID,
		&i.TitleModelID,
		&i.ImageModelID,
		&i.DiscussProbeModelID,
		&i.TtsModelID,
		&i.TranscriptionModelID,
		&i.BrowserContextID,
		&i.PersistFullToolResults,
		&i.ShowToolCallsInIm,
		&i.ToolApprovalConfig,
		&i.OverlayProvider,
		&i.OverlayEnabled,
		&i.OverlayConfig,
		&i.Metadata,
		&i.UpdatedAt,
	)
	return i, err
}
