// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBot = `-- name: CreateBot :one
INSERT INTO bots (owner_user_id, group_id, display_name, avatar_url, timezone, is_active, display_enabled, metadata, status, settings_override_mask)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  COALESCE(NULLIF($9::text, ''), 'ready'),
  COALESCE($10::jsonb, '{}'::jsonb)
)
RETURNING id, owner_user_id, group_id, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, display_enabled, settings_override_mask, metadata, created_at, updated_at
`

type CreateBotParams struct {
	OwnerUserID          pgtype.UUID `json:"owner_user_id"`
	GroupID              pgtype.UUID `json:"group_id"`
	DisplayName          pgtype.Text `json:"display_name"`
	AvatarUrl            pgtype.Text `json:"avatar_url"`
	Timezone             pgtype.Text `json:"timezone"`
	IsActive             bool        `json:"is_active"`
	DisplayEnabled       bool        `json:"display_enabled"`
	Metadata             []byte      `json:"metadata"`
	Status               string      `json:"status"`
	SettingsOverrideMask []byte      `json:"settings_override_mask"`
}

type CreateBotRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OwnerUserID          pgtype.UUID        `json:"owner_user_id"`
	GroupID              pgtype.UUID        `json:"group_id"`
	DisplayName          pgtype.Text        `json:"display_name"`
	AvatarUrl            pgtype.Text        `json:"avatar_url"`
	Timezone             pgtype.Text        `json:"timezone"`
	IsActive             bool               `json:"is_active"`
	Status               string             `json:"status"`
	Language             string             `json:"language"`
	ReasoningEnabled     bool               `json:"reasoning_enabled"`
	ReasoningEffort      string             `json:"reasoning_effort"`
	ChatModelID          pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID     pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID     pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled     bool               `json:"heartbeat_enabled"`
	HeartbeatInterval    int32              `json:"heartbeat_interval"`
	HeartbeatPrompt      string             `json:"heartbeat_prompt"`
	DisplayEnabled       bool               `json:"display_enabled"`
	SettingsOverrideMask []byte             `json:"settings_override_mask"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (CreateBotRow, error) {
	row := q.db.QueryRow(ctx, createBot,
		arg.OwnerUserID,
		arg.GroupID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Timezone,
		arg.IsActive,
		arg.DisplayEnabled,
		arg.Metadata,
		arg.Status,
		arg.SettingsOverrideMask,
	)
	var i CreateBotRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.GroupID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.DisplayEnabled,
		&i.SettingsOverrideMask,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBotByID = `-- name: DeleteBotByID :exec
DELETE FROM bots WHERE id = $1
`

func (q *Queries) DeleteBotByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBotByID, id)
	return err
}

const getBotByID = `-- name: GetBotByID :one
SELECT id, owner_user_id, group_id, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, display_enabled, compaction_enabled, compaction_threshold, compaction_ratio, compaction_model_id, settings_override_mask, metadata, created_at, updated_at
FROM bots
WHERE id = $1
`

type GetBotByIDRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OwnerUserID          pgtype.UUID        `json:"owner_user_id"`
	GroupID              pgtype.UUID        `json:"group_id"`
	DisplayName          pgtype.Text        `json:"display_name"`
	AvatarUrl            pgtype.Text        `json:"avatar_url"`
	Timezone             pgtype.Text        `json:"timezone"`
	IsActive             bool               `json:"is_active"`
	Status               string             `json:"status"`
	Language             string             `json:"language"`
	ReasoningEnabled     bool               `json:"reasoning_enabled"`
	ReasoningEffort      string             `json:"reasoning_effort"`
	ChatModelID          pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID     pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID     pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled     bool               `json:"heartbeat_enabled"`
	HeartbeatInterval    int32              `json:"heartbeat_interval"`
	HeartbeatPrompt      string             `json:"heartbeat_prompt"`
	DisplayEnabled       bool               `json:"display_enabled"`
	CompactionEnabled    bool               `json:"compaction_enabled"`
	CompactionThreshold  int32              `json:"compaction_threshold"`
	CompactionRatio      int32              `json:"compaction_ratio"`
	CompactionModelID    pgtype.UUID        `json:"compaction_model_id"`
	SettingsOverrideMask []byte             `json:"settings_override_mask"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetBotByID(ctx context.Context, id pgtype.UUID) (GetBotByIDRow, error) {
	row := q.db.QueryRow(ctx, getBotByID, id)
	var i GetBotByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.GroupID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.DisplayEnabled,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionRatio,
		&i.CompactionModelID,
		&i.SettingsOverrideMask,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotHeartbeatConfig = `-- name: GetBotHeartbeatConfig :one
SELECT
  bots.id,
  bots.owner_user_id,
  bots.status,
  CASE
    WHEN bots.group_id IS NOT NULL
      AND NOT COALESCE((bots.settings_override_mask->>'heartbeat_enabled')::boolean, false)
      THEN COALESCE(bot_group_settings.heartbeat_enabled, false)
    ELSE bots.heartbeat_enabled
  END::boolean AS heartbeat_enabled,
  CASE
    WHEN bots.group_id IS NOT NULL
      AND NOT COALESCE((bots.settings_override_mask->>'heartbeat_interval')::boolean, false)
      THEN COALESCE(bot_group_settings.heartbeat_interval, 30)
    ELSE bots.heartbeat_interval
  END::integer AS heartbeat_interval,
  CASE
    WHEN bots.group_id IS NOT NULL
      AND NOT COALESCE((bots.settings_override_mask->>'heartbeat_prompt')::boolean, false)
      THEN COALESCE(bot_group_settings.heartbeat_prompt, '')
    ELSE bots.heartbeat_prompt
  END::text AS heartbeat_prompt
FROM bots
LEFT JOIN bot_group_settings ON bot_group_settings.group_id = bots.group_id
WHERE bots.id = $1
`

type GetBotHeartbeatConfigRow struct {
	ID                pgtype.UUID `json:"id"`
	OwnerUserID       pgtype.UUID `json:"owner_user_id"`
	Status            string      `json:"status"`
	HeartbeatEnabled  bool        `json:"heartbeat_enabled"`
	HeartbeatInterval int32       `json:"heartbeat_interval"`
	HeartbeatPrompt   string      `json:"heartbeat_prompt"`
}

func (q *Queries) GetBotHeartbeatConfig(ctx context.Context, id pgtype.UUID) (GetBotHeartbeatConfigRow, error) {
	row := q.db.QueryRow(ctx, getBotHeartbeatConfig, id)
	var i GetBotHeartbeatConfigRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Status,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
	)
	return i, err
}

const listAccessibleBots = `-- name: ListAccessibleBots :many
SELECT bots.id, bots.owner_user_id, bots.group_id, bots.display_name, bots.avatar_url, bots.timezone, bots.is_active, bots.status, bots.language, bots.reasoning_enabled, bots.reasoning_effort, bots.chat_model_id, bots.search_provider_id, bots.memory_provider_id, bots.heartbeat_enabled, bots.heartbeat_interval, bots.heartbeat_prompt, bots.display_enabled, bots.settings_override_mask, bots.metadata, bots.created_at, bots.updated_at
FROM bots
LEFT JOIN bot_groups ON bot_groups.id = bots.group_id
WHERE bots.owner_user_id = $1
  OR bot_groups.visibility IN ('organization', 'public')
  OR EXISTS (
    SELECT 1
    FROM iam_principal_roles pr
    JOIN iam_roles r ON r.id = pr.role_id
    JOIN iam_role_permissions rp ON rp.role_id = r.id
    JOIN iam_permissions p ON p.id = rp.permission_id
    WHERE p.key = 'bot.read'
      AND pr.resource_type = 'bot'
      AND (pr.resource_id = bots.id OR pr.resource_id IS NULL)
      AND (
        (pr.principal_type = 'user' AND pr.principal_id = $1)
        OR (
          pr.principal_type = 'group'
          AND pr.principal_id IN (
            SELECT group_id FROM iam_group_members WHERE user_id = $1
          )
        )
      )
  )
  OR EXISTS (
    SELECT 1
    FROM iam_principal_roles pr
    JOIN iam_roles r ON r.id = pr.role_id
    JOIN iam_role_permissions rp ON rp.role_id = r.id
    JOIN iam_permissions p ON p.id = rp.permission_id
    WHERE p.key = 'bot_group.read'
      AND pr.resource_type = 'bot_group'
      AND bots.group_id IS NOT NULL
      AND (pr.resource_id = bots.group_id OR pr.resource_id IS NULL)
      AND (
        (pr.principal_type = 'user' AND pr.principal_id = $1)
        OR (
          pr.principal_type = 'group'
          AND pr.principal_id IN (
            SELECT group_id FROM iam_group_members WHERE user_id = $1
          )
        )
      )
  )
  OR EXISTS (
    SELECT 1
    FROM iam_principal_roles pr
    JOIN iam_roles r ON r.id = pr.role_id
    JOIN iam_role_permissions rp ON rp.role_id = r.id
    JOIN iam_permissions p ON p.id = rp.permission_id
    WHERE p.key = 'system.admin'
      AND pr.resource_type = 'system'
      AND pr.resource_id IS NULL
      AND (
        (pr.principal_type = 'user' AND pr.principal_id = $1)
        OR (
          pr.principal_type = 'group'
          AND pr.principal_id IN (
            SELECT group_id FROM iam_group_members WHERE user_id = $1
          )
        )
      )
  )
ORDER BY bots.created_at DESC
`

type ListAccessibleBotsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OwnerUserID          pgtype.UUID        `json:"owner_user_id"`
	GroupID              pgtype.UUID        `json:"group_id"`
	DisplayName          pgtype.Text        `json:"display_name"`
	AvatarUrl            pgtype.Text        `json:"avatar_url"`
	Timezone             pgtype.Text        `json:"timezone"`
	IsActive             bool               `json:"is_active"`
	Status               string             `json:"status"`
	Language             string             `json:"language"`
	ReasoningEnabled     bool               `json:"reasoning_enabled"`
	ReasoningEffort      string             `json:"reasoning_effort"`
	ChatModelID          pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID     pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID     pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled     bool               `json:"heartbeat_enabled"`
	HeartbeatInterval    int32              `json:"heartbeat_interval"`
	HeartbeatPrompt      string             `json:"heartbeat_prompt"`
	DisplayEnabled       bool               `json:"display_enabled"`
	SettingsOverrideMask []byte             `json:"settings_override_mask"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAccessibleBots(ctx context.Context, userID pgtype.UUID) ([]ListAccessibleBotsRow, error) {
	rows, err := q.db.Query(ctx, listAccessibleBots, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessibleBotsRow
	for rows.Next() {
		var i ListAccessibleBotsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.GroupID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Timezone,
			&i.IsActive,
			&i.Status,
			&i.Language,
			&i.ReasoningEnabled,
			&i.ReasoningEffort,
			&i.ChatModelID,
			&i.SearchProviderID,
			&i.MemoryProviderID,
			&i.HeartbeatEnabled,
			&i.HeartbeatInterval,
			&i.HeartbeatPrompt,
			&i.DisplayEnabled,
			&i.SettingsOverrideMask,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBotsByOwner = `-- name: ListBotsByOwner :many
SELECT id, owner_user_id, group_id, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, display_enabled, settings_override_mask, metadata, created_at, updated_at
FROM bots
WHERE owner_user_id = $1
ORDER BY created_at DESC
`

type ListBotsByOwnerRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OwnerUserID          pgtype.UUID        `json:"owner_user_id"`
	GroupID              pgtype.UUID        `json:"group_id"`
	DisplayName          pgtype.Text        `json:"display_name"`
	AvatarUrl            pgtype.Text        `json:"avatar_url"`
	Timezone             pgtype.Text        `json:"timezone"`
	IsActive             bool               `json:"is_active"`
	Status               string             `json:"status"`
	Language             string             `json:"language"`
	ReasoningEnabled     bool               `json:"reasoning_enabled"`
	ReasoningEffort      string             `json:"reasoning_effort"`
	ChatModelID          pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID     pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID     pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled     bool               `json:"heartbeat_enabled"`
	HeartbeatInterval    int32              `json:"heartbeat_interval"`
	HeartbeatPrompt      string             `json:"heartbeat_prompt"`
	DisplayEnabled       bool               `json:"display_enabled"`
	SettingsOverrideMask []byte             `json:"settings_override_mask"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListBotsByOwner(ctx context.Context, ownerUserID pgtype.UUID) ([]ListBotsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listBotsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBotsByOwnerRow
	for rows.Next() {
		var i ListBotsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.GroupID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Timezone,
			&i.IsActive,
			&i.Status,
			&i.Language,
			&i.ReasoningEnabled,
			&i.ReasoningEffort,
			&i.ChatModelID,
			&i.SearchProviderID,
			&i.MemoryProviderID,
			&i.HeartbeatEnabled,
			&i.HeartbeatInterval,
			&i.HeartbeatPrompt,
			&i.DisplayEnabled,
			&i.SettingsOverrideMask,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeartbeatEnabledBots = `-- name: ListHeartbeatEnabledBots :many
WITH effective AS (
  SELECT
    bots.id,
    bots.owner_user_id,
    bots.status,
    CASE
      WHEN bots.group_id IS NOT NULL
        AND NOT COALESCE((bots.settings_override_mask->>'heartbeat_enabled')::boolean, false)
        THEN COALESCE(bot_group_settings.heartbeat_enabled, false)
      ELSE bots.heartbeat_enabled
    END::boolean AS heartbeat_enabled,
    CASE
      WHEN bots.group_id IS NOT NULL
        AND NOT COALESCE((bots.settings_override_mask->>'heartbeat_interval')::boolean, false)
        THEN COALESCE(bot_group_settings.heartbeat_interval, 30)
      ELSE bots.heartbeat_interval
    END::integer AS heartbeat_interval,
    CASE
      WHEN bots.group_id IS NOT NULL
        AND NOT COALESCE((bots.settings_override_mask->>'heartbeat_prompt')::boolean, false)
        THEN COALESCE(bot_group_settings.heartbeat_prompt, '')
      ELSE bots.heartbeat_prompt
    END::text AS heartbeat_prompt
  FROM bots
  LEFT JOIN bot_group_settings ON bot_group_settings.group_id = bots.group_id
)
SELECT id, owner_user_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt
FROM effective
WHERE heartbeat_enabled = true AND status = 'ready'
`

type ListHeartbeatEnabledBotsRow struct {
	ID                pgtype.UUID `json:"id"`
	OwnerUserID       pgtype.UUID `json:"owner_user_id"`
	HeartbeatEnabled  bool        `json:"heartbeat_enabled"`
	HeartbeatInterval int32       `json:"heartbeat_interval"`
	HeartbeatPrompt   string      `json:"heartbeat_prompt"`
}

func (q *Queries) ListHeartbeatEnabledBots(ctx context.Context) ([]ListHeartbeatEnabledBotsRow, error) {
	rows, err := q.db.Query(ctx, listHeartbeatEnabledBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHeartbeatEnabledBotsRow
	for rows.Next() {
		var i ListHeartbeatEnabledBotsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.HeartbeatEnabled,
			&i.HeartbeatInterval,
			&i.HeartbeatPrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBotOwner = `-- name: UpdateBotOwner :one
UPDATE bots
SET owner_user_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, owner_user_id, group_id, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, display_enabled, settings_override_mask, metadata, created_at, updated_at
`

type UpdateBotOwnerParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

type UpdateBotOwnerRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OwnerUserID          pgtype.UUID        `json:"owner_user_id"`
	GroupID              pgtype.UUID        `json:"group_id"`
	DisplayName          pgtype.Text        `json:"display_name"`
	AvatarUrl            pgtype.Text        `json:"avatar_url"`
	Timezone             pgtype.Text        `json:"timezone"`
	IsActive             bool               `json:"is_active"`
	Status               string             `json:"status"`
	Language             string             `json:"language"`
	ReasoningEnabled     bool               `json:"reasoning_enabled"`
	ReasoningEffort      string             `json:"reasoning_effort"`
	ChatModelID          pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID     pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID     pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled     bool               `json:"heartbeat_enabled"`
	HeartbeatInterval    int32              `json:"heartbeat_interval"`
	HeartbeatPrompt      string             `json:"heartbeat_prompt"`
	DisplayEnabled       bool               `json:"display_enabled"`
	SettingsOverrideMask []byte             `json:"settings_override_mask"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateBotOwner(ctx context.Context, arg UpdateBotOwnerParams) (UpdateBotOwnerRow, error) {
	row := q.db.QueryRow(ctx, updateBotOwner, arg.ID, arg.OwnerUserID)
	var i UpdateBotOwnerRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.GroupID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.DisplayEnabled,
		&i.SettingsOverrideMask,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBotProfile = `-- name: UpdateBotProfile :one
UPDATE bots
SET display_name = $1,
    avatar_url = $2,
    timezone = $3,
    is_active = $4,
    group_id = $5,
    display_enabled = $6,
    metadata = $7,
    updated_at = now()
WHERE id = $8
RETURNING id, owner_user_id, group_id, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, display_enabled, settings_override_mask, metadata, created_at, updated_at
`

type UpdateBotProfileParams struct {
	DisplayName    pgtype.Text `json:"display_name"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
	Timezone       pgtype.Text `json:"timezone"`
	IsActive       bool        `json:"is_active"`
	GroupID        pgtype.UUID `json:"group_id"`
	DisplayEnabled bool        `json:"display_enabled"`
	Metadata       []byte      `json:"metadata"`
	ID             pgtype.UUID `json:"id"`
}

type UpdateBotProfileRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OwnerUserID          pgtype.UUID        `json:"owner_user_id"`
	GroupID              pgtype.UUID        `json:"group_id"`
	DisplayName          pgtype.Text        `json:"display_name"`
	AvatarUrl            pgtype.Text        `json:"avatar_url"`
	Timezone             pgtype.Text        `json:"timezone"`
	IsActive             bool               `json:"is_active"`
	Status               string             `json:"status"`
	Language             string             `json:"language"`
	ReasoningEnabled     bool               `json:"reasoning_enabled"`
	ReasoningEffort      string             `json:"reasoning_effort"`
	ChatModelID          pgtype.UUID        `json:"chat_model_id"`
	SearchProviderID     pgtype.UUID        `json:"search_provider_id"`
	MemoryProviderID     pgtype.UUID        `json:"memory_provider_id"`
	HeartbeatEnabled     bool               `json:"heartbeat_enabled"`
	HeartbeatInterval    int32              `json:"heartbeat_interval"`
	HeartbeatPrompt      string             `json:"heartbeat_prompt"`
	DisplayEnabled       bool               `json:"display_enabled"`
	SettingsOverrideMask []byte             `json:"settings_override_mask"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateBotProfile(ctx context.Context, arg UpdateBotProfileParams) (UpdateBotProfileRow, error) {
	row := q.db.QueryRow(ctx, updateBotProfile,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Timezone,
		arg.IsActive,
		arg.GroupID,
		arg.DisplayEnabled,
		arg.Metadata,
		arg.ID,
	)
	var i UpdateBotProfileRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.GroupID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.DisplayEnabled,
		&i.SettingsOverrideMask,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBotStatus = `-- name: UpdateBotStatus :exec
UPDATE bots
SET status = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateBotStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateBotStatus(ctx context.Context, arg UpdateBotStatusParams) error {
	_, err := q.db.Exec(ctx, updateBotStatus, arg.ID, arg.Status)
	return err
}
