// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_connector_leases.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireChannelConnectorLease = `-- name: AcquireChannelConnectorLease :one
WITH upsert AS (
  INSERT INTO channel_connector_leases (
    channel_config_id,
    channel_type,
    owner_id,
    owner_instance_id,
    lease_version,
    expires_at
  ) VALUES (
    $1,
    $2,
    $3,
    $4,
    1,
    $5
  )
  ON CONFLICT (channel_config_id) DO UPDATE
  SET channel_type = EXCLUDED.channel_type,
      owner_id = EXCLUDED.owner_id,
      owner_instance_id = EXCLUDED.owner_instance_id,
      lease_version = channel_connector_leases.lease_version + 1,
      expires_at = EXCLUDED.expires_at,
      updated_at = now()
  WHERE channel_connector_leases.expires_at < now()
  RETURNING channel_config_id, channel_type, owner_id, owner_instance_id, lease_version, expires_at, created_at, updated_at
)
SELECT channel_config_id, channel_type, owner_id, owner_instance_id, lease_version, expires_at, created_at, updated_at FROM upsert
`

type AcquireChannelConnectorLeaseParams struct {
	ChannelConfigID pgtype.UUID        `json:"channel_config_id"`
	ChannelType     string             `json:"channel_type"`
	OwnerID         string             `json:"owner_id"`
	OwnerInstanceID string             `json:"owner_instance_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type AcquireChannelConnectorLeaseRow struct {
	ChannelConfigID pgtype.UUID        `json:"channel_config_id"`
	ChannelType     string             `json:"channel_type"`
	OwnerID         string             `json:"owner_id"`
	OwnerInstanceID string             `json:"owner_instance_id"`
	LeaseVersion    int64              `json:"lease_version"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) AcquireChannelConnectorLease(ctx context.Context, arg AcquireChannelConnectorLeaseParams) (AcquireChannelConnectorLeaseRow, error) {
	row := q.db.QueryRow(ctx, acquireChannelConnectorLease,
		arg.ChannelConfigID,
		arg.ChannelType,
		arg.OwnerID,
		arg.OwnerInstanceID,
		arg.ExpiresAt,
	)
	var i AcquireChannelConnectorLeaseRow
	err := row.Scan(
		&i.ChannelConfigID,
		&i.ChannelType,
		&i.OwnerID,
		&i.OwnerInstanceID,
		&i.LeaseVersion,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkChannelConnectorLease = `-- name: CheckChannelConnectorLease :one
SELECT EXISTS (
  SELECT 1
  FROM channel_connector_leases
  WHERE channel_config_id = $1
    AND owner_instance_id = $2
    AND lease_version = $3
    AND expires_at > now()
)::boolean
`

type CheckChannelConnectorLeaseParams struct {
	ChannelConfigID pgtype.UUID `json:"channel_config_id"`
	OwnerInstanceID string      `json:"owner_instance_id"`
	LeaseVersion    int64       `json:"lease_version"`
}

func (q *Queries) CheckChannelConnectorLease(ctx context.Context, arg CheckChannelConnectorLeaseParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkChannelConnectorLease, arg.ChannelConfigID, arg.OwnerInstanceID, arg.LeaseVersion)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getCurrentChannelConnectorLease = `-- name: GetCurrentChannelConnectorLease :one
SELECT channel_config_id, channel_type, owner_id, owner_instance_id, lease_version, expires_at, created_at, updated_at
FROM channel_connector_leases
WHERE channel_config_id = $1
`

func (q *Queries) GetCurrentChannelConnectorLease(ctx context.Context, channelConfigID pgtype.UUID) (ChannelConnectorLease, error) {
	row := q.db.QueryRow(ctx, getCurrentChannelConnectorLease, channelConfigID)
	var i ChannelConnectorLease
	err := row.Scan(
		&i.ChannelConfigID,
		&i.ChannelType,
		&i.OwnerID,
		&i.OwnerInstanceID,
		&i.LeaseVersion,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseChannelConnectorLease = `-- name: ReleaseChannelConnectorLease :execrows
DELETE FROM channel_connector_leases
WHERE channel_config_id = $1
  AND owner_instance_id = $2
  AND lease_version = $3
`

type ReleaseChannelConnectorLeaseParams struct {
	ChannelConfigID pgtype.UUID `json:"channel_config_id"`
	OwnerInstanceID string      `json:"owner_instance_id"`
	LeaseVersion    int64       `json:"lease_version"`
}

func (q *Queries) ReleaseChannelConnectorLease(ctx context.Context, arg ReleaseChannelConnectorLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseChannelConnectorLease, arg.ChannelConfigID, arg.OwnerInstanceID, arg.LeaseVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewChannelConnectorLease = `-- name: RenewChannelConnectorLease :one
UPDATE channel_connector_leases
SET expires_at = $1,
    updated_at = now()
WHERE channel_config_id = $2
  AND owner_instance_id = $3
  AND lease_version = $4
  AND expires_at > now()
RETURNING channel_config_id, channel_type, owner_id, owner_instance_id, lease_version, expires_at, created_at, updated_at
`

type RenewChannelConnectorLeaseParams struct {
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	ChannelConfigID pgtype.UUID        `json:"channel_config_id"`
	OwnerInstanceID string             `json:"owner_instance_id"`
	LeaseVersion    int64              `json:"lease_version"`
}

func (q *Queries) RenewChannelConnectorLease(ctx context.Context, arg RenewChannelConnectorLeaseParams) (ChannelConnectorLease, error) {
	row := q.db.QueryRow(ctx, renewChannelConnectorLease,
		arg.ExpiresAt,
		arg.ChannelConfigID,
		arg.OwnerInstanceID,
		arg.LeaseVersion,
	)
	var i ChannelConnectorLease
	err := row.Scan(
		&i.ChannelConfigID,
		&i.ChannelType,
		&i.OwnerID,
		&i.OwnerInstanceID,
		&i.LeaseVersion,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
