// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ackEventDelivery = `-- name: AckEventDelivery :one
UPDATE event_deliveries
SET delivered_at = now(),
    locked_by = NULL,
    locked_until = NULL,
    updated_at = now()
WHERE event_id = $1
  AND consumer_name = $2
  AND locked_by = $3
  AND delivered_at IS NULL
  AND dead_lettered_at IS NULL
RETURNING event_id, consumer_name, topic, partition_key, available_at, locked_by, locked_until, attempts, max_attempts, last_error, delivered_at, dead_lettered_at, created_at, updated_at
`

type AckEventDeliveryParams struct {
	EventID      pgtype.UUID `json:"event_id"`
	ConsumerName string      `json:"consumer_name"`
	LockedBy     pgtype.Text `json:"locked_by"`
}

func (q *Queries) AckEventDelivery(ctx context.Context, arg AckEventDeliveryParams) (EventDelivery, error) {
	row := q.db.QueryRow(ctx, ackEventDelivery, arg.EventID, arg.ConsumerName, arg.LockedBy)
	var i EventDelivery
	err := row.Scan(
		&i.EventID,
		&i.ConsumerName,
		&i.Topic,
		&i.PartitionKey,
		&i.AvailableAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.DeliveredAt,
		&i.DeadLetteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimEventDeliveries = `-- name: ClaimEventDeliveries :many
WITH claimed AS (
  SELECT event_deliveries.event_id, event_deliveries.consumer_name
  FROM event_deliveries
  WHERE event_deliveries.consumer_name = $1
    AND event_deliveries.topic = $2
    AND event_deliveries.delivered_at IS NULL
    AND event_deliveries.dead_lettered_at IS NULL
    AND event_deliveries.available_at <= now()
    AND (event_deliveries.locked_until IS NULL OR event_deliveries.locked_until <= now())
  ORDER BY event_deliveries.partition_key NULLS LAST, event_deliveries.available_at ASC, event_deliveries.created_at ASC
  LIMIT $3
  FOR UPDATE SKIP LOCKED
),
updated AS (
  UPDATE event_deliveries d
  SET locked_by = $4,
      locked_until = $5,
      attempts = d.attempts + 1,
      updated_at = now()
  FROM claimed
  WHERE d.event_id = claimed.event_id
    AND d.consumer_name = claimed.consumer_name
  RETURNING d.event_id, d.consumer_name, d.topic, d.partition_key, d.available_at, d.locked_by, d.locked_until, d.attempts, d.max_attempts, d.last_error, d.delivered_at, d.dead_lettered_at, d.created_at, d.updated_at
)
SELECT
  updated.event_id,
  updated.consumer_name,
  updated.topic,
  updated.partition_key,
  updated.available_at,
  updated.locked_by,
  updated.locked_until,
  updated.attempts,
  updated.max_attempts,
  updated.last_error,
  updated.delivered_at,
  updated.dead_lettered_at,
  updated.created_at,
  updated.updated_at,
  event_outbox.payload_type,
  event_outbox.payload,
  event_outbox.payload_json,
  event_outbox.idempotency_key,
  event_outbox.aggregate_type,
  event_outbox.aggregate_id,
  event_outbox.created_at AS event_created_at
FROM updated
JOIN event_outbox ON event_outbox.id = updated.event_id
ORDER BY updated.partition_key NULLS LAST, updated.available_at ASC, updated.created_at ASC
`

type ClaimEventDeliveriesParams struct {
	ConsumerName string             `json:"consumer_name"`
	Topic        string             `json:"topic"`
	LimitCount   int32              `json:"limit_count"`
	LockedBy     pgtype.Text        `json:"locked_by"`
	LockedUntil  pgtype.Timestamptz `json:"locked_until"`
}

type ClaimEventDeliveriesRow struct {
	EventID        pgtype.UUID        `json:"event_id"`
	ConsumerName   string             `json:"consumer_name"`
	Topic          string             `json:"topic"`
	PartitionKey   pgtype.Text        `json:"partition_key"`
	AvailableAt    pgtype.Timestamptz `json:"available_at"`
	LockedBy       pgtype.Text        `json:"locked_by"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	Attempts       int32              `json:"attempts"`
	MaxAttempts    int32              `json:"max_attempts"`
	LastError      pgtype.Text        `json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	DeadLetteredAt pgtype.Timestamptz `json:"dead_lettered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PayloadType    string             `json:"payload_type"`
	Payload        []byte             `json:"payload"`
	PayloadJson    []byte             `json:"payload_json"`
	IdempotencyKey string             `json:"idempotency_key"`
	AggregateType  pgtype.Text        `json:"aggregate_type"`
	AggregateID    pgtype.UUID        `json:"aggregate_id"`
	EventCreatedAt pgtype.Timestamptz `json:"event_created_at"`
}

func (q *Queries) ClaimEventDeliveries(ctx context.Context, arg ClaimEventDeliveriesParams) ([]ClaimEventDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimEventDeliveries,
		arg.ConsumerName,
		arg.Topic,
		arg.LimitCount,
		arg.LockedBy,
		arg.LockedUntil,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimEventDeliveriesRow
	for rows.Next() {
		var i ClaimEventDeliveriesRow
		if err := rows.Scan(
			&i.EventID,
			&i.ConsumerName,
			&i.Topic,
			&i.PartitionKey,
			&i.AvailableAt,
			&i.LockedBy,
			&i.LockedUntil,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.DeliveredAt,
			&i.DeadLetteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PayloadType,
			&i.Payload,
			&i.PayloadJson,
			&i.IdempotencyKey,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEventDeliveries = `-- name: CreateEventDeliveries :many
INSERT INTO event_deliveries (
  event_id,
  consumer_name,
  topic,
  partition_key,
  available_at,
  max_attempts
)
SELECT
  $1,
  unnest($2::text[]),
  $3,
  $4,
  $5,
  $6
ON CONFLICT (event_id, consumer_name) DO NOTHING
RETURNING event_id, consumer_name, topic, partition_key, available_at, locked_by, locked_until, attempts, max_attempts, last_error, delivered_at, dead_lettered_at, created_at, updated_at
`

type CreateEventDeliveriesParams struct {
	EventID       pgtype.UUID        `json:"event_id"`
	ConsumerNames []string           `json:"consumer_names"`
	Topic         string             `json:"topic"`
	PartitionKey  pgtype.Text        `json:"partition_key"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
	MaxAttempts   int32              `json:"max_attempts"`
}

func (q *Queries) CreateEventDeliveries(ctx context.Context, arg CreateEventDeliveriesParams) ([]EventDelivery, error) {
	rows, err := q.db.Query(ctx, createEventDeliveries,
		arg.EventID,
		arg.ConsumerNames,
		arg.Topic,
		arg.PartitionKey,
		arg.AvailableAt,
		arg.MaxAttempts,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventDelivery
	for rows.Next() {
		var i EventDelivery
		if err := rows.Scan(
			&i.EventID,
			&i.ConsumerName,
			&i.Topic,
			&i.PartitionKey,
			&i.AvailableAt,
			&i.LockedBy,
			&i.LockedUntil,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.DeliveredAt,
			&i.DeadLetteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deadLetterEventDelivery = `-- name: DeadLetterEventDelivery :one
UPDATE event_deliveries
SET last_error = $1,
    locked_by = NULL,
    locked_until = NULL,
    dead_lettered_at = now(),
    updated_at = now()
WHERE event_id = $2
  AND consumer_name = $3
  AND delivered_at IS NULL
RETURNING event_id, consumer_name, topic, partition_key, available_at, locked_by, locked_until, attempts, max_attempts, last_error, delivered_at, dead_lettered_at, created_at, updated_at
`

type DeadLetterEventDeliveryParams struct {
	LastError    pgtype.Text `json:"last_error"`
	EventID      pgtype.UUID `json:"event_id"`
	ConsumerName string      `json:"consumer_name"`
}

func (q *Queries) DeadLetterEventDelivery(ctx context.Context, arg DeadLetterEventDeliveryParams) (EventDelivery, error) {
	row := q.db.QueryRow(ctx, deadLetterEventDelivery, arg.LastError, arg.EventID, arg.ConsumerName)
	var i EventDelivery
	err := row.Scan(
		&i.EventID,
		&i.ConsumerName,
		&i.Topic,
		&i.PartitionKey,
		&i.AvailableAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.DeliveredAt,
		&i.DeadLetteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueEvent = `-- name: EnqueueEvent :one
INSERT INTO event_outbox (
  topic,
  payload_type,
  payload,
  payload_json,
  idempotency_key,
  aggregate_type,
  aggregate_id,
  partition_key
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
ON CONFLICT (idempotency_key) DO UPDATE
SET idempotency_key = EXCLUDED.idempotency_key
RETURNING id, topic, payload_type, payload, payload_json, idempotency_key, aggregate_type, aggregate_id, partition_key, created_at
`

type EnqueueEventParams struct {
	Topic          string      `json:"topic"`
	PayloadType    string      `json:"payload_type"`
	Payload        []byte      `json:"payload"`
	PayloadJson    []byte      `json:"payload_json"`
	IdempotencyKey string      `json:"idempotency_key"`
	AggregateType  pgtype.Text `json:"aggregate_type"`
	AggregateID    pgtype.UUID `json:"aggregate_id"`
	PartitionKey   pgtype.Text `json:"partition_key"`
}

func (q *Queries) EnqueueEvent(ctx context.Context, arg EnqueueEventParams) (EventOutbox, error) {
	row := q.db.QueryRow(ctx, enqueueEvent,
		arg.Topic,
		arg.PayloadType,
		arg.Payload,
		arg.PayloadJson,
		arg.IdempotencyKey,
		arg.AggregateType,
		arg.AggregateID,
		arg.PartitionKey,
	)
	var i EventOutbox
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.PayloadType,
		&i.Payload,
		&i.PayloadJson,
		&i.IdempotencyKey,
		&i.AggregateType,
		&i.AggregateID,
		&i.PartitionKey,
		&i.CreatedAt,
	)
	return i, err
}

const failEventDelivery = `-- name: FailEventDelivery :one
UPDATE event_deliveries
SET last_error = $1,
    locked_by = NULL,
    locked_until = NULL,
    available_at = CASE
      WHEN attempts >= max_attempts THEN available_at
      ELSE $2
    END,
    dead_lettered_at = CASE
      WHEN attempts >= max_attempts THEN now()
      ELSE dead_lettered_at
    END,
    updated_at = now()
WHERE event_id = $3
  AND consumer_name = $4
  AND locked_by = $5
  AND delivered_at IS NULL
  AND dead_lettered_at IS NULL
RETURNING event_id, consumer_name, topic, partition_key, available_at, locked_by, locked_until, attempts, max_attempts, last_error, delivered_at, dead_lettered_at, created_at, updated_at
`

type FailEventDeliveryParams struct {
	LastError       pgtype.Text        `json:"last_error"`
	NextAvailableAt pgtype.Timestamptz `json:"next_available_at"`
	EventID         pgtype.UUID        `json:"event_id"`
	ConsumerName    string             `json:"consumer_name"`
	LockedBy        pgtype.Text        `json:"locked_by"`
}

func (q *Queries) FailEventDelivery(ctx context.Context, arg FailEventDeliveryParams) (EventDelivery, error) {
	row := q.db.QueryRow(ctx, failEventDelivery,
		arg.LastError,
		arg.NextAvailableAt,
		arg.EventID,
		arg.ConsumerName,
		arg.LockedBy,
	)
	var i EventDelivery
	err := row.Scan(
		&i.EventID,
		&i.ConsumerName,
		&i.Topic,
		&i.PartitionKey,
		&i.AvailableAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.DeliveredAt,
		&i.DeadLetteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventDelivery = `-- name: GetEventDelivery :one
SELECT event_id, consumer_name, topic, partition_key, available_at, locked_by, locked_until, attempts, max_attempts, last_error, delivered_at, dead_lettered_at, created_at, updated_at
FROM event_deliveries
WHERE event_id = $1
  AND consumer_name = $2
`

type GetEventDeliveryParams struct {
	EventID      pgtype.UUID `json:"event_id"`
	ConsumerName string      `json:"consumer_name"`
}

func (q *Queries) GetEventDelivery(ctx context.Context, arg GetEventDeliveryParams) (EventDelivery, error) {
	row := q.db.QueryRow(ctx, getEventDelivery, arg.EventID, arg.ConsumerName)
	var i EventDelivery
	err := row.Scan(
		&i.EventID,
		&i.ConsumerName,
		&i.Topic,
		&i.PartitionKey,
		&i.AvailableAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.DeliveredAt,
		&i.DeadLetteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
