// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: integration_api_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIntegrationAPIToken = `-- name: CreateIntegrationAPIToken :one
INSERT INTO integration_api_tokens (
  name,
  token_hash,
  scope_type,
  scope_bot_id,
  scope_bot_group_id,
  allowed_event_types,
  allowed_action_types,
  expires_at,
  created_by_user_id
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
RETURNING id, name, token_hash, scope_type, scope_bot_id, scope_bot_group_id, allowed_event_types, allowed_action_types, expires_at, disabled_at, last_used_at, created_by_user_id, created_at, updated_at
`

type CreateIntegrationAPITokenParams struct {
	Name               string             `json:"name"`
	TokenHash          string             `json:"token_hash"`
	ScopeType          string             `json:"scope_type"`
	ScopeBotID         pgtype.UUID        `json:"scope_bot_id"`
	ScopeBotGroupID    pgtype.UUID        `json:"scope_bot_group_id"`
	AllowedEventTypes  []byte             `json:"allowed_event_types"`
	AllowedActionTypes []byte             `json:"allowed_action_types"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedByUserID    pgtype.UUID        `json:"created_by_user_id"`
}

func (q *Queries) CreateIntegrationAPIToken(ctx context.Context, arg CreateIntegrationAPITokenParams) (IntegrationApiToken, error) {
	row := q.db.QueryRow(ctx, createIntegrationAPIToken,
		arg.Name,
		arg.TokenHash,
		arg.ScopeType,
		arg.ScopeBotID,
		arg.ScopeBotGroupID,
		arg.AllowedEventTypes,
		arg.AllowedActionTypes,
		arg.ExpiresAt,
		arg.CreatedByUserID,
	)
	var i IntegrationApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.ScopeType,
		&i.ScopeBotID,
		&i.ScopeBotGroupID,
		&i.AllowedEventTypes,
		&i.AllowedActionTypes,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.LastUsedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIntegrationAPIToken = `-- name: DeleteIntegrationAPIToken :exec
DELETE FROM integration_api_tokens
WHERE id = $1
`

func (q *Queries) DeleteIntegrationAPIToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIntegrationAPIToken, id)
	return err
}

const disableAllIntegrationAPITokens = `-- name: DisableAllIntegrationAPITokens :exec
UPDATE integration_api_tokens
SET disabled_at = COALESCE(disabled_at, now()),
    updated_at = now()
WHERE disabled_at IS NULL
`

func (q *Queries) DisableAllIntegrationAPITokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, disableAllIntegrationAPITokens)
	return err
}

const disableIntegrationAPIToken = `-- name: DisableIntegrationAPIToken :one
UPDATE integration_api_tokens
SET disabled_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, name, token_hash, scope_type, scope_bot_id, scope_bot_group_id, allowed_event_types, allowed_action_types, expires_at, disabled_at, last_used_at, created_by_user_id, created_at, updated_at
`

func (q *Queries) DisableIntegrationAPIToken(ctx context.Context, id pgtype.UUID) (IntegrationApiToken, error) {
	row := q.db.QueryRow(ctx, disableIntegrationAPIToken, id)
	var i IntegrationApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.ScopeType,
		&i.ScopeBotID,
		&i.ScopeBotGroupID,
		&i.AllowedEventTypes,
		&i.AllowedActionTypes,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.LastUsedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationAPITokenByHash = `-- name: GetIntegrationAPITokenByHash :one
SELECT id, name, token_hash, scope_type, scope_bot_id, scope_bot_group_id, allowed_event_types, allowed_action_types, expires_at, disabled_at, last_used_at, created_by_user_id, created_at, updated_at
FROM integration_api_tokens
WHERE token_hash = $1
`

func (q *Queries) GetIntegrationAPITokenByHash(ctx context.Context, tokenHash string) (IntegrationApiToken, error) {
	row := q.db.QueryRow(ctx, getIntegrationAPITokenByHash, tokenHash)
	var i IntegrationApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.ScopeType,
		&i.ScopeBotID,
		&i.ScopeBotGroupID,
		&i.AllowedEventTypes,
		&i.AllowedActionTypes,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.LastUsedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationAPITokenByID = `-- name: GetIntegrationAPITokenByID :one
SELECT id, name, token_hash, scope_type, scope_bot_id, scope_bot_group_id, allowed_event_types, allowed_action_types, expires_at, disabled_at, last_used_at, created_by_user_id, created_at, updated_at
FROM integration_api_tokens
WHERE id = $1
`

func (q *Queries) GetIntegrationAPITokenByID(ctx context.Context, id pgtype.UUID) (IntegrationApiToken, error) {
	row := q.db.QueryRow(ctx, getIntegrationAPITokenByID, id)
	var i IntegrationApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.ScopeType,
		&i.ScopeBotID,
		&i.ScopeBotGroupID,
		&i.AllowedEventTypes,
		&i.AllowedActionTypes,
		&i.ExpiresAt,
		&i.DisabledAt,
		&i.LastUsedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrationAPITokens = `-- name: ListIntegrationAPITokens :many
SELECT id, name, token_hash, scope_type, scope_bot_id, scope_bot_group_id, allowed_event_types, allowed_action_types, expires_at, disabled_at, last_used_at, created_by_user_id, created_at, updated_at
FROM integration_api_tokens
ORDER BY created_at DESC
`

func (q *Queries) ListIntegrationAPITokens(ctx context.Context) ([]IntegrationApiToken, error) {
	rows, err := q.db.Query(ctx, listIntegrationAPITokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationApiToken
	for rows.Next() {
		var i IntegrationApiToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.ScopeType,
			&i.ScopeBotID,
			&i.ScopeBotGroupID,
			&i.AllowedEventTypes,
			&i.AllowedActionTypes,
			&i.ExpiresAt,
			&i.DisabledAt,
			&i.LastUsedAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchIntegrationAPITokenUsed = `-- name: TouchIntegrationAPITokenUsed :exec
UPDATE integration_api_tokens
SET last_used_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchIntegrationAPITokenUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchIntegrationAPITokenUsed, id)
	return err
}
