// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: structured_data.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStructuredDataAudit = `-- name: CreateStructuredDataAudit :one
INSERT INTO structured_data_audit (
  space_id,
  actor_type,
  actor_user_id,
  actor_bot_id,
  operation,
  statement,
  success,
  error,
  row_count,
  duration_ms
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
RETURNING id, space_id, actor_type, actor_user_id, actor_bot_id, operation, statement, success, error, row_count, duration_ms, created_at
`

type CreateStructuredDataAuditParams struct {
	SpaceID     pgtype.UUID `json:"space_id"`
	ActorType   string      `json:"actor_type"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	ActorBotID  pgtype.UUID `json:"actor_bot_id"`
	Operation   string      `json:"operation"`
	Statement   string      `json:"statement"`
	Success     bool        `json:"success"`
	Error       string      `json:"error"`
	RowCount    int64       `json:"row_count"`
	DurationMs  int64       `json:"duration_ms"`
}

func (q *Queries) CreateStructuredDataAudit(ctx context.Context, arg CreateStructuredDataAuditParams) (StructuredDataAudit, error) {
	row := q.db.QueryRow(ctx, createStructuredDataAudit,
		arg.SpaceID,
		arg.ActorType,
		arg.ActorUserID,
		arg.ActorBotID,
		arg.Operation,
		arg.Statement,
		arg.Success,
		arg.Error,
		arg.RowCount,
		arg.DurationMs,
	)
	var i StructuredDataAudit
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ActorType,
		&i.ActorUserID,
		&i.ActorBotID,
		&i.Operation,
		&i.Statement,
		&i.Success,
		&i.Error,
		&i.RowCount,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const createStructuredDataSpace = `-- name: CreateStructuredDataSpace :one
INSERT INTO structured_data_spaces (
  owner_type,
  owner_bot_id,
  owner_bot_group_id,
  schema_name,
  role_name,
  display_name,
  metadata
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, owner_type, owner_bot_id, owner_bot_group_id, schema_name, role_name, display_name, metadata, created_at, updated_at
`

type CreateStructuredDataSpaceParams struct {
	OwnerType       string      `json:"owner_type"`
	OwnerBotID      pgtype.UUID `json:"owner_bot_id"`
	OwnerBotGroupID pgtype.UUID `json:"owner_bot_group_id"`
	SchemaName      string      `json:"schema_name"`
	RoleName        string      `json:"role_name"`
	DisplayName     string      `json:"display_name"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) CreateStructuredDataSpace(ctx context.Context, arg CreateStructuredDataSpaceParams) (StructuredDataSpace, error) {
	row := q.db.QueryRow(ctx, createStructuredDataSpace,
		arg.OwnerType,
		arg.OwnerBotID,
		arg.OwnerBotGroupID,
		arg.SchemaName,
		arg.RoleName,
		arg.DisplayName,
		arg.Metadata,
	)
	var i StructuredDataSpace
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerBotID,
		&i.OwnerBotGroupID,
		&i.SchemaName,
		&i.RoleName,
		&i.DisplayName,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStructuredDataGrant = `-- name: DeleteStructuredDataGrant :exec
DELETE FROM structured_data_grants
WHERE id = $1
`

func (q *Queries) DeleteStructuredDataGrant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStructuredDataGrant, id)
	return err
}

const getStructuredDataGrantByID = `-- name: GetStructuredDataGrantByID :one
SELECT id, space_id, target_type, target_bot_id, target_bot_group_id, privileges, created_by_user_id, created_at, updated_at
FROM structured_data_grants
WHERE id = $1
`

func (q *Queries) GetStructuredDataGrantByID(ctx context.Context, id pgtype.UUID) (StructuredDataGrant, error) {
	row := q.db.QueryRow(ctx, getStructuredDataGrantByID, id)
	var i StructuredDataGrant
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.TargetType,
		&i.TargetBotID,
		&i.TargetBotGroupID,
		&i.Privileges,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStructuredDataSpaceByBot = `-- name: GetStructuredDataSpaceByBot :one
SELECT id, owner_type, owner_bot_id, owner_bot_group_id, schema_name, role_name, display_name, metadata, created_at, updated_at
FROM structured_data_spaces
WHERE owner_type = 'bot'
  AND owner_bot_id = $1
`

func (q *Queries) GetStructuredDataSpaceByBot(ctx context.Context, ownerBotID pgtype.UUID) (StructuredDataSpace, error) {
	row := q.db.QueryRow(ctx, getStructuredDataSpaceByBot, ownerBotID)
	var i StructuredDataSpace
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerBotID,
		&i.OwnerBotGroupID,
		&i.SchemaName,
		&i.RoleName,
		&i.DisplayName,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStructuredDataSpaceByBotGroup = `-- name: GetStructuredDataSpaceByBotGroup :one
SELECT id, owner_type, owner_bot_id, owner_bot_group_id, schema_name, role_name, display_name, metadata, created_at, updated_at
FROM structured_data_spaces
WHERE owner_type = 'bot_group'
  AND owner_bot_group_id = $1
`

func (q *Queries) GetStructuredDataSpaceByBotGroup(ctx context.Context, ownerBotGroupID pgtype.UUID) (StructuredDataSpace, error) {
	row := q.db.QueryRow(ctx, getStructuredDataSpaceByBotGroup, ownerBotGroupID)
	var i StructuredDataSpace
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerBotID,
		&i.OwnerBotGroupID,
		&i.SchemaName,
		&i.RoleName,
		&i.DisplayName,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStructuredDataSpaceByID = `-- name: GetStructuredDataSpaceByID :one
SELECT id, owner_type, owner_bot_id, owner_bot_group_id, schema_name, role_name, display_name, metadata, created_at, updated_at
FROM structured_data_spaces
WHERE id = $1
`

func (q *Queries) GetStructuredDataSpaceByID(ctx context.Context, id pgtype.UUID) (StructuredDataSpace, error) {
	row := q.db.QueryRow(ctx, getStructuredDataSpaceByID, id)
	var i StructuredDataSpace
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.OwnerBotID,
		&i.OwnerBotGroupID,
		&i.SchemaName,
		&i.RoleName,
		&i.DisplayName,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStructuredDataGrantsBySpace = `-- name: ListStructuredDataGrantsBySpace :many
SELECT id, space_id, target_type, target_bot_id, target_bot_group_id, privileges, created_by_user_id, created_at, updated_at
FROM structured_data_grants
WHERE space_id = $1
ORDER BY target_type ASC, created_at DESC
`

func (q *Queries) ListStructuredDataGrantsBySpace(ctx context.Context, spaceID pgtype.UUID) ([]StructuredDataGrant, error) {
	rows, err := q.db.Query(ctx, listStructuredDataGrantsBySpace, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StructuredDataGrant
	for rows.Next() {
		var i StructuredDataGrant
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.TargetType,
			&i.TargetBotID,
			&i.TargetBotGroupID,
			&i.Privileges,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStructuredDataSpaces = `-- name: ListStructuredDataSpaces :many
SELECT id, owner_type, owner_bot_id, owner_bot_group_id, schema_name, role_name, display_name, metadata, created_at, updated_at
FROM structured_data_spaces
ORDER BY owner_type ASC, created_at DESC
`

func (q *Queries) ListStructuredDataSpaces(ctx context.Context) ([]StructuredDataSpace, error) {
	rows, err := q.db.Query(ctx, listStructuredDataSpaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StructuredDataSpace
	for rows.Next() {
		var i StructuredDataSpace
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerBotID,
			&i.OwnerBotGroupID,
			&i.SchemaName,
			&i.RoleName,
			&i.DisplayName,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStructuredDataSpacesForBotActor = `-- name: ListStructuredDataSpacesForBotActor :many
SELECT DISTINCT s.id, s.owner_type, s.owner_bot_id, s.owner_bot_group_id, s.schema_name, s.role_name, s.display_name, s.metadata, s.created_at, s.updated_at
FROM structured_data_spaces s
LEFT JOIN structured_data_grants g ON g.space_id = s.id
WHERE
  (s.owner_type = 'bot' AND s.owner_bot_id = $1)
  OR (
    $2::uuid IS NOT NULL
    AND s.owner_type = 'bot_group'
    AND s.owner_bot_group_id = $2
  )
  OR (g.target_type = 'bot' AND g.target_bot_id = $1)
  OR (
    $2::uuid IS NOT NULL
    AND g.target_type = 'bot_group'
    AND g.target_bot_group_id = $2
  )
ORDER BY s.owner_type ASC, s.created_at DESC
`

type ListStructuredDataSpacesForBotActorParams struct {
	BotID      pgtype.UUID `json:"bot_id"`
	BotGroupID pgtype.UUID `json:"bot_group_id"`
}

func (q *Queries) ListStructuredDataSpacesForBotActor(ctx context.Context, arg ListStructuredDataSpacesForBotActorParams) ([]StructuredDataSpace, error) {
	rows, err := q.db.Query(ctx, listStructuredDataSpacesForBotActor, arg.BotID, arg.BotGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StructuredDataSpace
	for rows.Next() {
		var i StructuredDataSpace
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerBotID,
			&i.OwnerBotGroupID,
			&i.SchemaName,
			&i.RoleName,
			&i.DisplayName,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStructuredDataGrantForBot = `-- name: UpsertStructuredDataGrantForBot :one
INSERT INTO structured_data_grants (
  space_id,
  target_type,
  target_bot_id,
  privileges,
  created_by_user_id
) VALUES (
  $1,
  'bot',
  $2,
  $3,
  $4
)
ON CONFLICT (space_id, target_bot_id) WHERE target_type = 'bot'
DO UPDATE SET
  privileges = EXCLUDED.privileges,
  updated_at = now()
RETURNING id, space_id, target_type, target_bot_id, target_bot_group_id, privileges, created_by_user_id, created_at, updated_at
`

type UpsertStructuredDataGrantForBotParams struct {
	SpaceID         pgtype.UUID `json:"space_id"`
	TargetBotID     pgtype.UUID `json:"target_bot_id"`
	Privileges      []string    `json:"privileges"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) UpsertStructuredDataGrantForBot(ctx context.Context, arg UpsertStructuredDataGrantForBotParams) (StructuredDataGrant, error) {
	row := q.db.QueryRow(ctx, upsertStructuredDataGrantForBot,
		arg.SpaceID,
		arg.TargetBotID,
		arg.Privileges,
		arg.CreatedByUserID,
	)
	var i StructuredDataGrant
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.TargetType,
		&i.TargetBotID,
		&i.TargetBotGroupID,
		&i.Privileges,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStructuredDataGrantForBotGroup = `-- name: UpsertStructuredDataGrantForBotGroup :one
INSERT INTO structured_data_grants (
  space_id,
  target_type,
  target_bot_group_id,
  privileges,
  created_by_user_id
) VALUES (
  $1,
  'bot_group',
  $2,
  $3,
  $4
)
ON CONFLICT (space_id, target_bot_group_id) WHERE target_type = 'bot_group'
DO UPDATE SET
  privileges = EXCLUDED.privileges,
  updated_at = now()
RETURNING id, space_id, target_type, target_bot_id, target_bot_group_id, privileges, created_by_user_id, created_at, updated_at
`

type UpsertStructuredDataGrantForBotGroupParams struct {
	SpaceID          pgtype.UUID `json:"space_id"`
	TargetBotGroupID pgtype.UUID `json:"target_bot_group_id"`
	Privileges       []string    `json:"privileges"`
	CreatedByUserID  pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) UpsertStructuredDataGrantForBotGroup(ctx context.Context, arg UpsertStructuredDataGrantForBotGroupParams) (StructuredDataGrant, error) {
	row := q.db.QueryRow(ctx, upsertStructuredDataGrantForBotGroup,
		arg.SpaceID,
		arg.TargetBotGroupID,
		arg.Privileges,
		arg.CreatedByUserID,
	)
	var i StructuredDataGrant
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.TargetType,
		&i.TargetBotID,
		&i.TargetBotGroupID,
		&i.Privileges,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
