name: "memoh"
services:
  migrate:
    build:
      context: ../../..
      dockerfile: deploy/docker/production/Dockerfile.server
      args:
        - VERSION=${MEMOH_VERSION:-dev}
        - COMMIT_HASH=${MEMOH_COMMIT:-unknown}
        - BUILD_TIME=${MEMOH_BUILD_TIME:-unknown}

  server:
    build:
      context: ../../..
      dockerfile: deploy/docker/production/Dockerfile.server
      args:
        - VERSION=${MEMOH_VERSION:-dev}
        - COMMIT_HASH=${MEMOH_COMMIT:-unknown}
        - BUILD_TIME=${MEMOH_BUILD_TIME:-unknown}

  sparse:
    build:
      context: ../../..
      dockerfile: deploy/docker/production/Dockerfile.sparse

  browser:
    build:
      context: ../../..
      dockerfile: deploy/docker/production/Dockerfile.browser
